use std::fs;
use std::io::{BufRead, BufReader, Read, Seek, SeekFrom};
use std::path::Path;
use std::time::SystemTime;

use chrono::{DateTime, Utc};
use serde_json::Value;

use super::models::JsonlEntry;
use super::paths::get_claude_dir;

/// Session metadata extracted in a single pass
pub struct SessionMetadata {
    pub first_message: Option<String>,
    pub message_timestamp: Option<String>,
    pub last_message_timestamp: Option<String>,
    pub model: Option<String>,
}

/// Extracts all session metadata in a single file read pass
/// This is much more efficient than calling extract_first_user_message,
/// extract_last_message_timestamp, and extract_session_model separately
pub fn extract_session_metadata<P: AsRef<Path>>(jsonl_path: P) -> SessionMetadata {
    let file = match fs::File::open(jsonl_path) {
        Ok(file) => file,
        Err(_) => return SessionMetadata {
            first_message: None,
            message_timestamp: None,
            last_message_timestamp: None,
            model: None,
        },
    };

    let reader = BufReader::new(file);
    let mut first_message: Option<String> = None;
    let mut message_timestamp: Option<String> = None;
    let mut last_timestamp: Option<String> = None;
    let mut model: Option<String> = None;

    for line in reader.lines() {
        let line = match line {
            Ok(l) => l,
            Err(_) => continue,
        };

        let entry: Value = match serde_json::from_str(&line) {
            Ok(v) => v,
            Err(_) => continue,
        };

        // Extract model (from system init or assistant message)
        if model.is_none() {
            if let Some(model_str) = entry.get("model").and_then(|m| m.as_str()) {
                model = Some(model_str.to_string());
            } else if let Some(message) = entry.get("message") {
                if let Some(model_str) = message.get("model").and_then(|m| m.as_str()) {
                    model = Some(model_str.to_string());
                }
            }
        }

        // Track last timestamp from any message
        if entry.get("message").is_some() {
            if let Some(ts) = entry.get("timestamp").and_then(|t| t.as_str()) {
                last_timestamp = Some(ts.to_string());
            }
        }

        // Extract first user message (only if not found yet)
        if first_message.is_none() {
            if let Ok(parsed_entry) = serde_json::from_value::<JsonlEntry>(entry.clone()) {
                if let Some(message) = parsed_entry.message {
                    if message.role.as_deref() == Some("user") {
                        if let Some(content_value) = message.content {
                            let mut extracted_text = String::new();
                            let mut has_text_content = false;

                            if let Some(text) = content_value.as_str() {
                                extracted_text = text.to_string();
                                has_text_content = !text.trim().is_empty();
                            } else if let Some(arr) = content_value.as_array() {
                                for item in arr {
                                    if let Some(item_type) = item.get("type").and_then(|t| t.as_str()) {
                                        if item_type == "text" {
                                            if let Some(text) = item.get("text").and_then(|t| t.as_str()) {
                                                extracted_text.push_str(text);
                                                has_text_content = true;
                                            }
                                        }
                                    }
                                }
                            }

                            if has_text_content
                                && !extracted_text.contains("Caveat: The messages below were generated by the user while running local commands")
                                && !extracted_text.starts_with("<command-name>")
                                && !extracted_text.starts_with("<local-command-stdout>")
                                && !extracted_text.contains("Warmup")
                            {
                                first_message = Some(extracted_text);
                                message_timestamp = parsed_entry.timestamp;
                            }
                        }
                    }
                }
            }
        }
    }

    SessionMetadata {
        first_message,
        message_timestamp,
        last_message_timestamp: last_timestamp,
        model,
    }
}

/// Extracts the first valid user message from a JSONL file
#[allow(dead_code)]
pub fn extract_first_user_message<P: AsRef<Path>>(
    jsonl_path: P,
) -> (Option<String>, Option<String>) {
    let file = match fs::File::open(jsonl_path) {
        Ok(file) => file,
        Err(_) => return (None, None),
    };

    let reader = BufReader::new(file);

    for line in reader.lines() {
        if let Ok(line) = line {
            if let Ok(entry) = serde_json::from_str::<JsonlEntry>(&line) {
                if let Some(message) = entry.message {
                    if message.role.as_deref() == Some("user") {
                        if let Some(content_value) = message.content {
                            let mut extracted_text = String::new();
                            let mut has_text_content = false;

                            if let Some(text) = content_value.as_str() {
                                extracted_text = text.to_string();
                                has_text_content = !text.trim().is_empty();
                            } else if let Some(arr) = content_value.as_array() {
                                for item in arr {
                                    if let Some(item_type) =
                                        item.get("type").and_then(|t| t.as_str())
                                    {
                                        if item_type == "text" {
                                            if let Some(text) =
                                                item.get("text").and_then(|t| t.as_str())
                                            {
                                                extracted_text.push_str(text);
                                                has_text_content = true;
                                            }
                                        }
                                    }
                                }
                            }

                            if !has_text_content {
                                continue;
                            }

                            if extracted_text.contains("Caveat: The messages below were generated by the user while running local commands") {
                                continue;
                            }

                            if extracted_text.starts_with("<command-name>")
                                || extracted_text.starts_with("<local-command-stdout>")
                            {
                                continue;
                            }

                            if extracted_text.contains("Warmup") {
                                continue;
                            }

                            return (Some(extracted_text), entry.timestamp);
                        }
                    }
                }
            }
        }
    }

    (None, None)
}

/// Extracts the timestamp of the last message using reverse file reading
/// Much faster than reading the entire file for large session files
#[allow(dead_code)]
pub fn extract_last_message_timestamp<P: AsRef<Path>>(jsonl_path: P) -> Option<String> {
    let mut file = match fs::File::open(jsonl_path.as_ref()) {
        Ok(file) => file,
        Err(_) => return None,
    };

    // Read last 8KB of the file (usually enough to find the last message)
    let file_size = file.metadata().ok()?.len();
    let read_size = std::cmp::min(file_size, 8192) as usize;
    let seek_pos = file_size - read_size as u64;

    if file.seek(SeekFrom::Start(seek_pos)).is_err() {
        return None;
    }

    let mut buffer = vec![0u8; read_size];
    if file.read_exact(&mut buffer).is_err() {
        return None;
    }

    let content = String::from_utf8_lossy(&buffer);
    let mut last_timestamp: Option<String> = None;

    // Parse lines from the tail chunk
    for line in content.lines() {
        if let Ok(entry) = serde_json::from_str::<JsonlEntry>(line) {
            if entry.message.is_some() {
                if let Some(timestamp) = entry.timestamp {
                    last_timestamp = Some(timestamp);
                }
            }
        }
    }

    // If we found a timestamp in the tail, return it
    if last_timestamp.is_some() {
        return last_timestamp;
    }

    // Fallback: read the full file (only for very small files or edge cases)
    let file = match fs::File::open(jsonl_path) {
        Ok(file) => file,
        Err(_) => return None,
    };
    let reader = BufReader::new(file);
    for line in reader.lines() {
        if let Ok(line) = line {
            if let Ok(entry) = serde_json::from_str::<JsonlEntry>(&line) {
                if entry.message.is_some() {
                    if let Some(timestamp) = entry.timestamp {
                        last_timestamp = Some(timestamp);
                    }
                }
            }
        }
    }
    last_timestamp
}

/// Extracts the model used in the session from a JSONL file
/// Only reads the first 30 lines since model info is always near the top
#[allow(dead_code)]
pub fn extract_session_model<P: AsRef<Path>>(jsonl_path: P) -> Option<String> {
    let file = match fs::File::open(jsonl_path) {
        Ok(file) => file,
        Err(_) => return None,
    };

    let reader = BufReader::new(file);

    for line in reader.lines().take(30) {
        if let Ok(line) = line {
            if let Ok(entry) = serde_json::from_str::<Value>(&line) {
                if let Some(model_str) = entry.get("model").and_then(|m| m.as_str()) {
                    return Some(model_str.to_string());
                } else if let Some(message) = entry.get("message") {
                    if let Some(model_str) = message.get("model").and_then(|m| m.as_str()) {
                        return Some(model_str.to_string());
                    }
                }
            }
        }
    }

    None
}

/// Loads the JSONL history for a specific session
/// Also loads subagent messages from agent-*.jsonl files and merges them
pub fn load_session_history(session_id: &str, project_id: &str) -> Result<Vec<Value>, String> {
    log::info!(
        "Loading session history for session: {} in project: {}",
        session_id,
        project_id
    );

    let claude_dir = get_claude_dir().map_err(|e| e.to_string())?;
    let project_dir = claude_dir.join("projects").join(project_id);
    let session_path = project_dir.join(format!("{}.jsonl", session_id));

    if !session_path.exists() {
        return Err(format!("Session file not found: {}", session_id));
    }

    let file_metadata =
        fs::metadata(&session_path).map_err(|e| format!("Failed to read file metadata: {}", e))?;
    let base_time = file_metadata
        .modified()
        .unwrap_or_else(|_| SystemTime::now());

    let file =
        fs::File::open(&session_path).map_err(|e| format!("Failed to open session file: {}", e))?;

    let reader = BufReader::new(file);
    let mut messages = Vec::new();

    let mut agent_to_tool_use_id: std::collections::HashMap<String, String> =
        std::collections::HashMap::new();

    for line in reader.lines() {
        if let Ok(line) = line {
            if let Ok(json) = serde_json::from_str::<Value>(&line) {
                if let Some(content) = json
                    .get("message")
                    .and_then(|m| m.get("content"))
                    .and_then(|c| c.as_array())
                {
                    for item in content {
                        if item.get("type").and_then(|t| t.as_str()) == Some("tool_result") {
                            if let (Some(tool_use_id), Some(agent_id)) = (
                                item.get("tool_use_id").and_then(|t| t.as_str()),
                                json.get("toolUseResult")
                                    .and_then(|r| r.get("agentId"))
                                    .and_then(|a| a.as_str()),
                            ) {
                                agent_to_tool_use_id
                                    .insert(agent_id.to_string(), tool_use_id.to_string());
                            }
                        }
                    }
                }
                messages.push(json);
            }
        }
    }

    if !agent_to_tool_use_id.is_empty() {
        if let Ok(entries) = fs::read_dir(&project_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if let Some(file_name) = path.file_name().and_then(|n| n.to_str()) {
                    if file_name.starts_with("agent-") && file_name.ends_with(".jsonl") {
                        let agent_id = file_name
                            .strip_prefix("agent-")
                            .and_then(|s| s.strip_suffix(".jsonl"))
                            .unwrap_or("");

                        if let Some(tool_use_id) = agent_to_tool_use_id.get(agent_id) {
                            if let Ok(file) = fs::File::open(&path) {
                                let reader = BufReader::new(file);
                                for line in reader.lines() {
                                    if let Ok(line) = line {
                                        if let Ok(mut json) = serde_json::from_str::<Value>(&line) {
                                            let subagent_session_id =
                                                json.get("sessionId").and_then(|s| s.as_str());
                                            if subagent_session_id == Some(session_id) {
                                                json["parent_tool_use_id"] =
                                                    Value::String(tool_use_id.clone());
                                                messages.push(json);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    messages.sort_by(|a, b| {
        let ts_a = a.get("timestamp").and_then(|t| t.as_str()).unwrap_or("");
        let ts_b = b.get("timestamp").and_then(|t| t.as_str()).unwrap_or("");
        ts_a.cmp(ts_b)
    });

    let messages_count = messages.len();
    for (i, message) in messages.iter_mut().enumerate() {
        let message_type = message.get("type").and_then(|t| t.as_str()).unwrap_or("");
        let time_offset = (messages_count - i - 1) as u64 * 5;
        let message_time = base_time - std::time::Duration::from_secs(time_offset);
        let timestamp_iso = DateTime::<Utc>::from(message_time).to_rfc3339();

        match message_type {
            "user" => {
                if !message.get("sentAt").is_some() {
                    message["sentAt"] = Value::String(timestamp_iso.clone());
                }
            }
            _ => {
                if !message.get("receivedAt").is_some() {
                    message["receivedAt"] = Value::String(timestamp_iso.clone());
                }
            }
        }
    }

    log::info!(
        "Loaded {} total messages (including subagent messages)",
        messages.len()
    );
    Ok(messages)
}
